# Link the C runtime into Windows executables, so they run on machines
# without the Visual C++ redistributable installed.
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
