[package]
name = "scanner"
version = "0.2.0"
edition = "2024"
license = "AGPL-3.0-only"

[dependencies]
airspy = { path = "../drivers/airspy" , version = "0.2.0" }
audio = { path = "../drivers/audio" , version = "0.2.0" }
radiocore = { path = "../radiocore" , version = "0.2.0" }
chrono = { version = "0.4", default-features = false, features = ["clock"] }
ctrlc = "3"
rusqlite = { version = "0.40.2", features = ["bundled"] }
ureq = "2"
roxmltree = "0.21.1"
