[package]
name = "scanner"
version = "0.1.0"
edition = "2024"

[dependencies]
airspy = { path = "../drivers/airspy" }
audio = { path = "../drivers/audio" }
radiocore = { path = "../radiocore" }
chrono = { version = "0.4", default-features = false, features = ["clock"] }
ctrlc = "3"
rusqlite = { version = "0.40.2", features = ["bundled"] }
